---
- hosts: all
  tasks:
    - name: Installing conda package
      ansible.builtin.package:
        name: conda
        state: present

    - name: Import role andrewrothstein.conda-env
      ansible.builtin.import_role:
        name: andrewrothstein.conda-env
      vars:
        conda_env_conda_dir: /usr
        conda_env_name: my-environment
        conda_env_environment: files/environment.yml
